apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: aks-demo-webapp-source
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/fabricekrebs/demo-webapp
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: aks-demo-webapp
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./manifests
  prune: true
  sourceRef:
    kind: GitRepository
    name: aks-demo-webapp-source
  targetNamespace: aks-demo-webapp
  serviceAccountName: flux-applier
