apiVersion: v1
kind: Namespace
metadata:
  name: aks-store-demo
  labels:
    name: aks-store-demo
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: aks-store-demo-source
  namespace: aks-store-demo
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/Azure-Samples/aks-store-demo
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: aks-store-demo
  namespace: aks-store-demo
spec:
  interval: 10m0s
  path: ./kustomize/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: aks-store-demo-source
  targetNamespace: aks-store-demo
