apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: aks-store-demo-source
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/Azure-Samples/aks-store-demo
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: aks-store-demo
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./kustomize/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: aks-store-demo-source
  targetNamespace: aks-store-demo
  serviceAccountName: flux-applier
  patches:
  - target:
      kind: Service
      name: store-front
    patch: |-
      - op: replace
        path: /spec/type
        value: NodePort
      - op: add
        path: /spec/allocateLoadBalancerNodePorts
        value: null
  - target:
      kind: Service
      name: store-admin
    patch: |-
      - op: replace
        path: /spec/type
        value: NodePort
      - op: add
        path: /spec/allocateLoadBalancerNodePorts
        value: null

